import './participer.css';

const form = document.querySelector('#contribution-form');
const text = form.elements.textContent;
const count = document.querySelector('#text-count');
const filesInput = document.querySelector('#files');
const fileList = document.querySelector('#file-list');
const error = document.querySelector('#form-error');
let selectedFiles = [];
let audioBlob = null, recorder = null, chunks = [], elapsed = 0, timer = null;
const record = document.querySelector('#record-button'), pause = document.querySelector('#pause-button'), stop = document.querySelector('#stop-button'), time = document.querySelector('#recording-time'), audio = document.querySelector('#audio-preview'), removeAudio = document.querySelector('#remove-audio'), audioStatus = document.querySelector('#audio-status');
text.addEventListener('input', () => count.textContent = `${text.value.length.toLocaleString('fr-FR')} / 20 000 caractères`);
function renderFiles(){fileList.innerHTML='';selectedFiles.forEach((file,index)=>{const li=document.createElement('li');li.innerHTML=`<span>${file.name} <small>(${(file.size/1024/1024).toFixed(2)} Mo)</small></span>`;const button=document.createElement('button');button.type='button';button.textContent='Supprimer';button.onclick=()=>{selectedFiles.splice(index,1);renderFiles()};li.append(button);fileList.append(li)})}
function addFiles(files){for(const file of files){if(file.size>10*1024*1024){error.textContent=`${file.name} dépasse la limite de 10 Mo.`;continue}if(!/\.(pdf|doc|docx|txt|jpe?g|png)$/i.test(file.name)){error.textContent=`${file.name} n’est pas un format autorisé.`;continue}selectedFiles.push(file)}renderFiles()}
filesInput.addEventListener('change',()=>addFiles(filesInput.files));
document.querySelector('.dropzone').addEventListener('dragover',event=>event.preventDefault());document.querySelector('.dropzone').addEventListener('drop',event=>{event.preventDefault();addFiles(event.dataTransfer.files)});
const renderTime=()=>{time.textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`};
record.addEventListener('click',async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(MediaRecorder.isTypeSupported);recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];elapsed=0;renderTime();recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());audioBlob=new Blob(chunks,{type:recorder.mimeType});audio.src=URL.createObjectURL(audioBlob);audio.hidden=false;removeAudio.hidden=false;audioStatus.textContent='Enregistrement prêt à être envoyé.'};recorder.start(1000);timer=setInterval(()=>{elapsed++;renderTime();if(elapsed>=600)stop.click()},1000);record.hidden=true;pause.hidden=false;stop.hidden=false;audioStatus.textContent='Microphone en cours d’utilisation.'}catch{audioStatus.textContent='Le microphone est indisponible ou son accès a été refusé.'}});
pause.addEventListener('click',()=>{if(!recorder)return;if(recorder.state==='recording'){recorder.pause();pause.textContent='Reprendre';clearInterval(timer)}else{recorder.resume();pause.textContent='Pause';timer=setInterval(()=>{elapsed++;renderTime()},1000)}});stop.addEventListener('click',()=>{if(recorder&&recorder.state!=='inactive'){recorder.stop();clearInterval(timer)}record.hidden=false;pause.hidden=true;stop.hidden=true});removeAudio.addEventListener('click',()=>{audioBlob=null;audio.hidden=true;removeAudio.hidden=true;audio.removeAttribute('src');audioStatus.textContent='Enregistrement supprimé.'});
form.addEventListener('submit',async event=>{event.preventDefault();error.textContent='';if(!form.checkValidity()){form.reportValidity();return}if(!text.value.trim()&&!audioBlob&&!selectedFiles.length){error.textContent='Ajoutez un texte, une note vocale ou au moins un document.';return}const button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent='Envoi en cours…';try{const data=new FormData(form);data.delete('files');selectedFiles.forEach(file=>data.append('files',file));if(audioBlob)data.append('audio',audioBlob,audioBlob.type.includes('mp4')?'contribution.m4a':'contribution.webm');const response=await fetch('/api/contributions',{method:'POST',body:data});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Impossible d’enregistrer la contribution.');form.hidden=true;document.querySelector('#reference').textContent=payload.reference;document.querySelector('#confirmation').hidden=false;document.querySelector('#confirmation').scrollIntoView({behavior:'smooth'})}catch(err){error.textContent=err.message;button.disabled=false;button.innerHTML='Envoyer ma contribution <span>→</span>'}});
